Minha lição 04
icaro-freire/estat_2020.1 pull request #29
Opened 2021-03-20 22:23 UTC by helenborges

2021-03-21 14:53 UTC, icaro-freire requested changes
Helen ... Que bom que você está fazendo as tarefas da disciplina.
Peço que você modifique os comandos da "imagem".
Há um erro lá, pois a figura não aparece.

Veja se são as aspas.

Depois disso, mande-me novamente a atividade, para que eu possa dar-te a nota máxima.

:wink:

2021-03-21 15:07 UTC, helenborges commented
Bom dia professor, eu modifiquei a imagem, coloquei e tirei as aspas só que mesmo assim a imagem na estava aparecendo, fiz uma última modificação e ao clicar no link da imagem eu fui direcionada a imagem.
Eu tentei colocar da forma que o senhor solicitou porém não obtive êxito.
Vou tentar modificar mais uma vez.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
From: Ícaro Vidal Freire ***@***.***>
Sent: Sunday, March 21, 2021 11:53:20 AM
To: icaro-freire/estat_2020.1 ***@***.***>
Cc: Helen Borges ***@***.***>; Author ***@***.***>
Subject: Re: [icaro-freire/estat_2020.1] Minha lição 04 (#29)


@icaro-freire requested changes on this pull request.

Helen ... Que bom que você está fazendo as tarefas da disciplina.
Peço que você modifique os comandos da "imagem".
Há um erro lá, pois a figura não aparece.

Veja se são as aspas.

Depois disso, mande-me novamente a atividade, para que eu possa dar-te a nota máxima.

😉

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/icaro-freire/estat_2020.1/pull/29#pullrequestreview-617028557>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATAT3VAK53PFBK4DNFEECATTEYB6BANCNFSM4ZQ3ZMUA>.

2021-03-25 00:48 UTC, helenborges commented
Lição 05

2021-03-27 00:51 UTC, icaro-freire requested changes
Olá, Helen!

Vi que você realizou 50% da atividade, pois não criou um documento GitHub com os comandos do R.

Peço que inclua tal arquivo em seu repositório e atualiza esse Pull Request.
Caso contrário, a sua nota será apenas 50% do valor total.
Você conseguirá, tenho certeza!

Abração!

2021-05-28 00:42 UTC, merged