Merge pull request #1 from icaro-freire/main
icaro-freire/estat_2020.1 pull request #30
Opened 2021-03-25 00:35 UTC by SheilaRosa

atualização da atividade 4

2021-03-25 00:51 UTC, SheilaRosa commented
atualização do Fork

2021-03-25 02:56 UTC, icaro-freire requested changes
Prezada Sheila, tudo em paz?
Fico feliz que você esteja fazendo as atividades da disciplina.

Peço que você refaça essa lição e torne a mandar-me um Pull Request.
Os motivos são os seguintes:
   - Você não colocou o link corretamente de seu repositório;
   - Você não criou o texto solicitado em Markdown.
 Aguardo suas modificações para que a lição seja pontuada.

Abraços!

2021-03-27 00:55 UTC, icaro-freire requested changes
Olá, Sheila!

Vejo que suas modificações ainda não foram realizadas.

Vou te ajudar fazendo um Pull Request e ensinando o passo a passo, em seu próprio texto.
Depois refaça e atualize esse Pull Request aqui.

Abração!

2021-03-27 10:17 UTC, SheilaRosa commented
Bom Dia!
O texto que fiz e o link q coloquei, estão incorretos?
Vou olha novamente.




Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
From: Ícaro Vidal Freire ***@***.***>
Sent: Friday, March 26, 2021 9:55:23 PM
To: icaro-freire/estat_2020.1 ***@***.***>
Cc: Sheila_Rosa ***@***.***>; Author ***@***.***>
Subject: Re: [icaro-freire/estat_2020.1] Merge pull request #1 from icaro-freire/main (#30)


@icaro-freire requested changes on this pull request.

Olá, Sheila!

Vejo que suas modificações ainda não foram realizadas.

Vou te ajudar fazendo um Pull Request e ensinando o passo a passo, em seu próprio texto.
Depois refaça e atualize esse Pull Request aqui.

Abração!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/icaro-freire/estat_2020.1/pull/30#pullrequestreview-622602912>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATAG6H3EPNGULQVKTJ4Z233TFUUHXANCNFSM4ZYKTDKQ>.

2021-03-29 20:10 UTC, SheilaRosa commented
Boa Tarde! 
Já fiz as alterações na atividade.

2021-03-29 23:04 UTC, icaro-freire approved these changes
Ótimo!
Agora sim! =)
Parabéns!

2021-03-29 23:04 UTC, merged